### ISSUE TITLE
Information from the satellite product

### ISSUE THREAD

**Issue by vwmaus** [gilbertocamara/sits#6]
Is it possible to include other information from satellite product in the "sits_table" object? 

For example resolution, unit, projection, would be very appreciated... This would reduce the number of arguments for the user to set, for example in "sits_assess". 

Best,
Victor

**Comment by gilbertocamara** [comment]
This information is now available in the coverage object returned in  
the function:

sits_coverageWTSS


Quoting Victor Maus <notifications@github.com>:

> Is it possible to include other information from satellite product   
> in the "sits_table" object?
>
> For example resolution, unit, projection, would be very   
> appreciated... This would reduce the number of arguments for the   
> user to set, for example in "sits_assess".
>
> Best,
> Victor
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gilbertocamara/sits/issues/6



----------------------------------------------------------------
This message was sent using IMP, the Internet Messaging Program.

**Comment by vwmaus** [comment]
great, thanks!
